### ISSUE TITLE
Route delete/remove method

### ISSUE THREAD

**Issue by epiloque** [hapijs/call#19]
Hello,

How would one go about implementing route delete/remove method. I'm willing to write code & tests, but since I'm new to the Call's inner workings I wanted to hear from the community first.

Thank you

**Comment by hueniverse** [comment]
We don't support removing routes because hapi keeps too many cross links to make it a simple operation to reason about. I'm not completely opposed but I don't see the need and rather not spend the time required on the hapi side to sort it all out. There are a lot of edge cases to consider as plugins expect to be able to look things up during the request life cycle.

**Comment by mtharrison** [comment]
What's the problem you're looking to solve? Do you really need to delete the route from the router altogether? Or you just want it to be inaccessible due to some event at runtime? That would be quite easy to achieve.

**Comment by epiloque** [comment]
I have an edge case, I've ported call to the browser and I'm having difficulty implementing the remove method in a clean way. Would removing the route from Router.table.routes, Router.table.router & Router.ids be the correct way ?

**Comment by hueniverse** [comment]
This is not going to happen in call.
