### ISSUE TITLE
Dynamic paths with specific vhost have preference over static paths without specific vhost

### ISSUE THREAD

**Issue by rubennorte** [hapijs/call#25]
With this configuration of routes:

Route A:

```
{
  path: '/{slug}',
  vhost: 'sub.example.com'
}
```

Route B:

```
{
  path: '/robots.txt'
}
```

A is having priority over B. I think in this cases B should have a higher priority, don't you think?

I understand that at this moment, the router gets the routing table for the vhost and, if it is not defined, uses the default routing table. Would it be possible to merge those tables?

**Comment by rubennorte** [comment]
Any thoughts on this?

**Comment by AdriVanHoudt** [comment]
@hueniverse ?

**Comment by hueniverse** [comment]
I am not sure what's the right priority here. Right now, the logic is very clear - vhost takes priority over path. I am not thrilled with the idea of changing this, save as #12. Merging tables is also tricky because once a route is added to a table, we don't have logic to remove it since it is compiled into the full tree.

I'll leave this open but I am unlikely to change it unless I am in the mood for a major rewrite to also handle #12.
